project:
  type: website
  output-dir: docs

website:
  description: "Blog de Andres, hecho en Quarto."
  site-url: https://fruzciant.github.io/mi-blog/ 
  title: "Blog de Andres"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fruzciant
      - icon: twitter-x
        href: https://x.com/andr3s4maya

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    other-links:
      - text: Descargar PDF
        icon: file-pdf
        href: index.pdf
  pdf:
    documentclass: article
    papersize: letter
    toc: false
    colorlinks: true
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm